# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('card_type', models.IntegerField(choices=[(1, '发病卡'), (2, '死亡卡')])),
                ('icd_10_code', models.CharField(blank=True, max_length=8)),
                ('icd_o_code', models.CharField(blank=True, max_length=8)),
                ('patient_no', models.IntegerField()),
                ('hospitalized_no', models.IntegerField()),
                ('id_no', models.CharField(blank=True, max_length=18)),
                ('name', models.CharField(max_length=40)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')])),
                ('race', models.CharField(max_length=8)),
                ('birth_date', models.DateField()),
                ('exact_age', models.IntegerField()),
                ('marriage', models.CharField(max_length=4)),
                ('telephone', models.IntegerField()),
                ('occupation', models.CharField(max_length=8)),
                ('company', models.CharField(max_length=16)),
                ('census_register', models.CharField(max_length=64)),
                ('residence', models.CharField(max_length=64)),
                ('diagnosis', models.CharField(max_length=16)),
                ('pathology', models.CharField(max_length=8)),
                ('diagnose_type', models.IntegerField(choices=[(0, '死亡补发病'), (1, '临床'), (2, 'X线、CT、超声、内镜'), (3, '手术、尸检（无病理）'), (4, '生化、免疫'), (5, '细胞学、血片'), (6, '病理（继发）'), (7, '病理（原发）'), (8, '尸检（有病理）'), (9, '不详')])),
                ('diagnose_date', models.DateField()),
                ('diagnose_hospital', models.CharField(max_length=16)),
                ('follow_up', models.IntegerField(choices=[(1, '存活'), (2, '死亡'), (3, '移居'), (4, '失访'), (9, '不详')])),
                ('result', models.CharField(max_length=16)),
                ('death_date', models.DateField()),
                ('death_reason', models.CharField(max_length=16)),
                ('reporter', models.CharField(max_length=8)),
                ('death_point', models.CharField(max_length=16)),
                ('report_hospital', models.CharField(max_length=16)),
                ('report_date', models.DateField()),
                ('pre_diagnosis', models.CharField(blank=True, max_length=16)),
                ('pre_diagnose_date', models.DateField(blank=True)),
            ],
        ),
    ]
